### PR TITLE
swarm: fix Unwrap for DialError, implement Unwrap for TransportError

### PR DESCRIPTION
**Pull request by sukunrt**
fixes: https://github.com/libp2p/go-libp2p/issues/2436

Depends on #2460  #2461 
Blocked on go1.21 release.

### CODE REVIEW

**Review by marten-seemann — CHANGES_REQUESTED** [review]
There was a change in Go 1.20 that allows wrapping multiple errors. Should we use that new API?

We could simply wait until we drop Go 1.19 in a month, then we don't need to deal with any build flags now.

**Comment by sukunrt** [comment]
I don't mind waiting. This is not blocking anything.

**Comment by marten-seemann** [comment]
We can still get it into the next release. v0.30 won't happen before the Go 1.21 transition (quic-go forces us to do so, if we want to include v0.37).

**Comment by marten-seemann** [comment]
#2460 and #2461. @sukunrt can you rebase please?

**Review by marten-seemann — APPROVED** [review]

**Pull request merged**
