### PR TITLE
connmgr: fix concurrent map misuse.

### PR DESCRIPTION
**Pull request by cachalots**
fix https://github.com/libp2p/go-libp2p/issues/1847 https://github.com/ipfs/kubo/issues/9374
https://github.com/libp2p/go-libp2p/blob/21dc42bd72fc6064c27a098db680e94ced5a76d6/p2p/net/connmgr/connmgr.go#L450
Loop conns is not locked, causing concurrent map misuse.

This repair method needs to modify more code, so I didn't choose to use this method.
```
type peerInfos  []peerInfo

// replace to
type peerInfos struct {
	peerInfo []peerInfo
	segments segments
}
```

### CODE REVIEW

**Review by marten-seemann — CHANGES_REQUESTED** [review]
That doesn't seem like a very intuitive API. `peerInfo` is just a `[]peerInfo`, and has no (obvious) connection to `segments` (which just holds a `map` of `peerInfo`s).

**Comment by cachalots** [comment]
> That doesn't seem like a very intuitive API. `peerInfo` is just a `[]peerInfo`, and has no (obvious) connection to `segments` (which just holds a `map` of `peerInfo`s).

I just put forward this idea. The code just add parameter `segments` to the  method `SortByValueAndStreams` to get lock.

**Comment by p-shahi** [comment]
Thanks for the initiative and providing logs @cachalots! I will close this in favor of https://github.com/libp2p/go-libp2p/pull/1860

**Comment by MarcoPolo** [comment]
Thanks for looking into this @cachalots. I put a fix here: https://github.com/libp2p/go-libp2p/pull/1860. It's worth pointing out that this PR has two possible deadlocks. 

1. both left and right are in the same segment.
2. goroutine 1 locks A then B, goroutine 2 locks B then A.

s hard Concurrency i.

I'm closing this pr and proceeding with #1860 (feel free to give that a review!), but I appreciate the effort. In the mean time, if you're looking for other places to contribute you could take a look at: https://github.com/libp2p/go-libp2p/issues/1707 especially since you've already familiarized yourself with the connmgr.

**Pull request closed without merging**
