### PR TITLE
use standard library sha256 implementation for Go 1.21

### PR DESCRIPTION
**Pull request by Jorropo**
See rational and benchmarks in multiformats/go-multihash#173.

Fixes: #2308

### CODE REVIEW

**Review by marten-seemann — COMMENTED** [review]
Dep update is fine, but this is not enough to drop minio. We use it in the crypto package and in the noise package as well.

**Review by marten-seemann — COMMENTED** [review]
Change looks fine to me. Thank you @Jorropo!

I'll hold off my approval since this is not yet tested on CI (and _can't_ be tested, since quic-go currently makes it possible to even compile go-libp2p with Go 1.21).

**Comment by marten-seemann** [comment]
@Jorropo Can you please rebase and update go-multihash to v0.2.3? I'd like to include this in the v0.30 release later today, but I can't push to your branch.

**Comment by Jorropo** [comment]
@marten-seemann done

**Comment by Jorropo** [comment]
Unrelated autorelay failure, rerunning the test suite.

**Review by marten-seemann — APPROVED** [review]
Danke!

**Pull request merged**
