### PR TITLE
don't use the context to shut down the relay

### PR DESCRIPTION
**Pull request by marten-seemann**
Not a big fan of this change. I'd have preferred to save the `AutoRelay` on the `BasicHost`, but that's not possible (import cycle).

### CODE REVIEW

**Review by vyzo — COMMENTED** [review]
I don't like this proliferation of host wrappers either -- can't we just save the `close` function in the host and invoke that?
We can even compose multiple close functions into one this way for all dependent services.

**Comment by marten-seemann** [comment]
I thought of that, but I’m not sure if having a SetClose(closeFunc) method on the Host is nicer.

**Comment by vyzo** [comment]
we dont have to expose it in the interface; the constructor can just
collect what it needs. It can also be a slice of io.Closers that we store.

**Comment by vyzo** [comment]
Another, more convoluted abstraction is to track services by unique keys
and expose interface methods for managing that. This can also eliminate
atrocities like the basic host cast in lotus just to get to autonat.

But thats probably a more general discussion to be held here.

**Comment by marten-seemann** [comment]
We can’t put it in the constructor, as the autonat depends on the host.

Let’s keep wrapping for now, I think that’s the more idiomatic way to handle this in Go anyway.

**Comment by vyzo** [comment]
I meant in the libp2p constructor, *not* the object constructor; i'd rather
avoid the wrapping.

**Review by vyzo — APPROVED** [review]
actually I'll give the blessing; I am allergic to host wrapping, but on the same time I can't think of any really good reason not to wrap, so let's do it.

We should have the discussion about services at some point, so that we can eliminate wrapping altogether in the future.

**Comment by Stebalien** [comment]
Can I not pass in a set of abstract "service" constructors into the host? Of the form `func(Host) (io.Closer, error)`?

(note: fx/dependency injection would also fix this, we really need a way to "manage" libp2p services).

**Comment by marten-seemann** [comment]
> Can I not pass in a set of abstract "service" constructors into the host? Of the form func(Host) (io.Closer, error)?

I'd love to do this. We just need to figure out a way to pass options to that constructor.

**Pull request merged**
