### PR TITLE
chore: update libp2p to v0.21 in examples

### PR DESCRIPTION
**Pull request by Stebalien**

### CODE REVIEW

**Comment by Stebalien** [comment]
Hm. Looks like we need a DHT update.

**Comment by marten-seemann** [comment]
Our first generics error:
```
# github.com/rivo/uniseg
  Error: /Users/runner/go/pkg/mod/github.com/rivo/uniseg@v0.3.4/properties.go:130:6: missing function body
  Error: /Users/runner/go/pkg/mod/github.com/rivo/uniseg@v0.3.4/properties.go:130:20: syntax error: unexpected [, expecting (
  note: module requires Go 1.18
  Error: Process completed with exit code 2.
```

How's that possible? kad is tested with Go 1.17 as well.

**Comment by marten-seemann** [comment]
cc @laurentsenta, since you asked about the Go update

**Comment by Stebalien** [comment]
That's not kad, that was an other update. I'll go revert it.

**Comment by Stebalien** [comment]
Ok, now we're down to flakes (TestMaxAge).

**Review by marten-seemann — APPROVED** [review]
Thank you @Stebalien!

**Pull request merged**
