### PR TITLE
Fix "go vet" errors.

### PR DESCRIPTION
**Pull request by kevina**

### CODE REVIEW

**Comment by kevina** [comment]
There is one error I am not sure how to correctly fix:
```
p2p/host/basic/basic_host.go:182: the relayCancel function is not used on all paths (possible context leak)
p2p/host/basic/basic_host.go:186: this return statement may be reached without using the relayCancel var defined on line 182
```

**Comment by Stebalien** [comment]
@kevina two ways:

1. Just add a `_ = relayCancel`. Not a fan of this solution.
2. Always define the context (IMO, the correct solution).

Patch:

```patch
diff --git a/p2p/host/basic/basic_host.go b/p2p/host/basic/basic_host.go
index a2bd21e..890e473 100644
--- a/p2p/host/basic/basic_host.go
+++ b/p2p/host/basic/basic_host.go
@@ -115,6 +115,7 @@ type HostOpts struct {
 
 // NewHost constructs a new *BasicHost and activates it by attaching its stream and connection handlers to the given inet.Network.
 func NewHost(ctx context.Context, net inet.Network, opts *HostOpts) (*BasicHost, error) {
+	ctx, cancel := context.WithCancel(ctx)
 	h := &BasicHost{
 		network:    net,
 		mux:        msmux.NewMultistreamMuxer(),
@@ -123,6 +124,14 @@ func NewHost(ctx context.Context, net inet.Network, opts *HostOpts) (*BasicHost,
 		maResolver: madns.DefaultResolver,
 	}
 
+	h.proc = goprocess.WithTeardown(func() error {
+		cancel()
+		if h.natmgr != nil {
+			h.natmgr.Close()
+		}
+		return h.Network().Close()
+	})
+
 	if opts.MultistreamMuxer != nil {
 		h.mux = opts.MultistreamMuxer
 	}
@@ -162,25 +171,11 @@ func NewHost(ctx context.Context, net inet.Network, opts *HostOpts) (*BasicHost,
 		net.Notify(h.cmgr.Notifee())
 	}
 
-	var relayCtx context.Context
-	var relayCancel func()
-
-	h.proc = goprocess.WithTeardown(func() error {
-		if h.natmgr != nil {
-			h.natmgr.Close()
-		}
-		if relayCancel != nil {
-			relayCancel()
-		}
-		return h.Network().Close()
-	})
-
 	net.SetConnHandler(h.newConnHandler)
 	net.SetStreamHandler(h.newStreamHandler)
 
 	if opts.EnableRelay {
-		relayCtx, relayCancel = context.WithCancel(ctx)
-		err := circuit.AddRelayTransport(relayCtx, h, opts.RelayOpts...)
+		err := circuit.AddRelayTransport(ctx, h, opts.RelayOpts...)
 		if err != nil {
 			h.Close()
 			return nil, err
```

**Comment by Stebalien** [comment]
I've pushed that patch (ish, I put the cancel/natmngr.Close calls back in the original order).

**Comment by Stebalien** [comment]
@kevina can you review my change? If it looks fine to you, I'll merge this.

**Comment by kevina** [comment]
LGTM but I am would prefer @Kubuxu or @whyrusleeping have a look at it first.

**Pull request merged**
