### PR TITLE
Mulit-protocol app with protobufs

### PR DESCRIPTION
**Pull request by avive**
Merged fixes. Tested. Should be good to go!

### CODE REVIEW

**Comment by avive** [comment]
Looks like Travis complains about missing dep `github.com/golang/protobuf/proto`

**Comment by vyzo** [comment]
you need to use gogo protobuf.

**Comment by avive** [comment]
I'm familiar with goog. Unfortunately, this import is in the go generated file from the proto file.
Please consider adding `github.com/golang/protobuf/proto` as a GX dep to resolve. thanks!

**Comment by vyzo** [comment]
You need to generate the proto file with gogo protobuf; there is already a dependency for it.

**Comment by vyzo** [comment]
use `--gogo_out` or `--gogofast_out`; you will need to install it first.

**Comment by avive** [comment]
ok - I think I sorted out with my latest commit.

**Comment by avive** [comment]
ok, so the proto file is now generated with gogo as recommended but Travis is still upset. Local builds work.

**Comment by vyzo** [comment]
i think you might need to use the version in gx; do you mind if i fix this?

**Comment by vyzo** [comment]
oh i can't push to this.

**Comment by avive** [comment]
Please FIX - it is a major PITA to deal with GOGO

**Comment by vyzo** [comment]
I can't without opening a new PR in a feature branch where i can push.

**Comment by vyzo** [comment]
Or we can use the other PR, since the branch is still alive and open.

I will merge your master and update there.

**Comment by avive** [comment]
Can't you just open a PR such as this one so I can merge it? https://github.com/avive/go-libp2p/pull/1

**Comment by vyzo** [comment]
too much work, it's easier to use the extant pr; it will be the same commits.

**Comment by vyzo** [comment]
merged and regenerated in #280; closing this.
If you have futher fixes let me know and I can pull them from your master, but you really should be using a development branch for PRs.

**Pull request closed without merging**
