### PR TITLE
Consolidate abstractions and core types into go-libp2p-core (#28)

### LINKED ISSUE #647: go get -u fails with go 1.12.5, win64
Pretty straightforward, was just updating my modules as per usual (no code changed, just a routine module update). `go get -u` (with `GO111MODULES=on` in the GOPATH) seemed to be bugging out at transport-upgrader and basic host. Logs:

```zsh
go: finding github.com/whyrusleeping/mdns latest
# github.com/libp2p/go-libp2p-transport-upgrader
R:\Go\pkg\mod\github.com\libp2p\go-libp2p-transport-upgrader@v0.0.4\upgrader.go:80:12: undefined: ipnet.ForcePrivateNetwork
# github.com/libp2p/go-libp2p/p2p/host/basic
R:\Go\pkg\mod\github.com\libp2p\go-libp2p@v0.0.30\p2p\host\basic\basic_host.go:145:32: cannot use h (type *BasicHost) as type host.Host in argument to identify.NewIDService:
        *BasicHost does not implement host.Host (wrong type for Mux method)
                have Mux() *multistream.MultistreamMuxer
                want Mux() "github.com/libp2p/go-libp2p-core/protocol".Switch
R:\Go\pkg\mod\github.com\libp2p\go-libp2p@v0.0.30\p2p\host\basic\basic_host.go:172:32: cannot use h (type *BasicHost) as type host.Host in argument to ping.NewPingService:
        *BasicHost does not implement host.Host (wrong type for Mux method)
                have Mux() *multistream.MultistreamMuxer
                want Mux() "github.com/libp2p/go-libp2p-core/protocol".Switch
```

### PR DESCRIPTION
**Pull request by Stebalien**
fixes #647

### CODE REVIEW

**Comment by raulk** [comment]
Mind updating #601 instead with the new module versions?

**Comment by Stebalien** [comment]
Sure! I thought you were asleep. I was going to just go ahead and break all of libp2p for fun!

**Comment by Stebalien** [comment]
Actually, rebasing that is going to be painful. Mind if I just go with this one?

**Comment by Stebalien** [comment]
(closing as this doesn't catch discovery/routing)

**Pull request closed without merging**
