### PR TITLE
chore: testify fixes

### PR DESCRIPTION
**Pull request by dozyio**
* Updated a bunch of `require.Equals` to use the correct `expected, actual` format
* Replaced a few tests with `require` equivalents

### CODE REVIEW

**Comment by sukunrt** [comment]
Thanks for the PR!

>Replaced a few tests with require equivalents

Can we remove this set of changes from this PR? 

Using `t.Fatalf` etc is fine.

**Review by sukunrt — CHANGES_REQUESTED** [review]
Thanks for the PR!

    Replaced a few tests with require equivalents

Can we remove this set of changes from this PR?

Using t.Fatalf etc is fine.

**Comment by dozyio** [comment]
> Can we remove this set of changes from this PR?
> 
> Using t.Fatalf etc is fine.

done, thanks - let me know if you want anything else reverting

**Review by sukunrt — APPROVED** [review]

**Comment by sukunrt** [comment]
Thanks @dozyio

**Pull request merged**
