### PR TITLE
Update go-nat

### PR DESCRIPTION
**Pull request by Kubuxu**
resolves https://github.com/libp2p/go-libp2p/issues/93

### CODE REVIEW

**Comment by whyrusleeping** [comment]
@Kubuxu this updates go-nat, go-nat-pmp, jackpal/gateway and huin/goupnp ?

**Comment by whyrusleeping** [comment]
(i forgot about `gx diff` silly me)

**Comment by Kubuxu** [comment]
Yes, whole stack.

**Comment by whyrusleeping** [comment]
Now i wish i had some `gx changelog-diff` so i can just view whats changed in each of these packages... But that would require gx to track git versions (which it doesnt do yet :( )

**Comment by whyrusleeping** [comment]
Alright, this LGTM. I wish we had tests...

**Comment by Kubuxu** [comment]
Yeah, I can create PR on go-ipfs so we test if it builds with the rest of the system.

**Comment by Kubuxu** [comment]
I've run tests of go-ipfs, they were green: https://github.com/ipfs/go-ipfs/pull/3123

**Comment by whyrusleeping** [comment]
odd... the OSX CI is failing, but the build log only shows successful tests...

**Pull request merged**
