### PR TITLE
remove legacy mDNS implementation

### PR DESCRIPTION
**Pull request by marten-seemann**

### CODE REVIEW

**Comment by Stebalien** [comment]
Is there any reason not to leave this around for a while?

**Comment by marten-seemann** [comment]
Other than cleaning up code, not really. This is a fairly isolated change, so I'm ok with letting this sit around for a while.

**Comment by marten-seemann** [comment]
IPFS is removing legacy mDNS support in https://github.com/ipfs/go-ipfs/pull/9048. With our main legacy-mDNS customer gone, there's no need to keep this code around any longer.

**Review by Stebalien — APPROVED** [review]

**Comment by qdm12** [comment]
Hello here, I am having trouble upgrading from mdns_legacy to mdns in the Go Polkadot host Gossamer, I tried:

https://github.com/ChainSafe/gossamer/pull/2788/files#diff-9603d26d1ec8aa880ef24f64c01d9292bd21c3538eea0b06662c38220d831eddL47-R52

Does anyone has a better clue how to bump this further?

**Comment by Stebalien** [comment]
Not without knowing what the issue is... Let's move this conversation over to that PR (tag me there and let me know what's up).

**Pull request merged**
