### PR TITLE
Support generating custom x509 certificates

### PR DESCRIPTION
**Pull request by peterargue**
This PR was originally opened here https://github.com/libp2p/go-libp2p-tls/pull/99 and relates to this issue: fixes https://github.com/libp2p/go-libp2p/issues/1538

## Context

`libp2ptls.NewIdentity` generates a new `Identity` which includes an x509 certificate with a special signed extension which ties the TLS key pair to a libp2p network identity. In flow, we use this key pair to secure a gRPC interface which is accessible to nodes on the network as well as external public clients, allowing them to verify that they've connected to the correct staked node.

The current implementation of `NewIdentity` does not support customizing the certificate template, and uses default options that aren't compatible with standard TLS clients (e.g. Subject doesn't include a `cn` field).

## Proposal

This PR refactors keyToCertificate into 3 methods

* `GenerateSignedExtension` (exported), which generates the signed extension
* `certTemplate` which returns the default certificate template used to generate the self-signed certificate,
* `keyToCertificate`, which accepts an `x509.Certificate` template, adds the signed extension and returns the `tls.Certificate` object.

This PR also adds a new optional parameter to `NewIdentity`, which can provide a custom certificate template.

The changes are intended to be backwards compatible and add the ability for a caller to specify the x509 certificate fields they wish to include in the generated certificate.

### CODE REVIEW

**Comment by peterargue** [comment]
@marten-seemann here's the new PR

**Review by MarcoPolo — COMMENTED** [review]
This looks good to me, but I'll let @marten-seemann submit the approval. Thanks for this and moving the PR over here!

**Comment by peterargue** [comment]
@marten-seemann this look OK to you?

**Review by marten-seemann — COMMENTED** [review]
I added a few comments. Other than that, the code looks good to me.
We should probably also have a test where we perform a handshake using a custom certificate, to make sure things work end-to-end.

**Comment by peterargue** [comment]
Thanks @marten-seemann. I just pushed some changes addressing your comments.

**Review by MarcoPolo — APPROVED** [review]

**Comment by peterargue** [comment]
Hey @marten-seemann think this PR is ok to merge?

**Comment by marten-seemann** [comment]
Yes, it is. I approved it. But we won't merge it before the v0.21 release.

**Comment by MarcoPolo** [comment]
Right after https://github.com/libp2p/go-libp2p/pull/1648, we’ll merge this. We wanted to make this release pretty small and we’ve started running some smoke tests for v0.21.

**Comment by peterargue** [comment]
awesome. thanks!

**Pull request merged**
