### PR TITLE
swarm: fix swarm closed connection count

### PR DESCRIPTION
**Pull request by sukunrt**
fixes: https://github.com/libp2p/go-libp2p/issues/2113

### CODE REVIEW

**Comment by marten-seemann** [comment]
Nice debugging! Why did you decide to not move the `OpenedConnection` call to `addConn`?

**Comment by sukunrt** [comment]
I chose this because if we moved OpenedConnection to swarm.addConn we'd not track connections dropped [here](https://github.com/libp2p/go-libp2p/blob/master/p2p/net/swarm/limiter.go#L222-L225)
I thought this tracking of concurrent successful dials and some of them immediately dropped might be useful if we change something in the future. 
A fix I thought of was to drain ```w.resch``` [here](https://github.com/libp2p/go-libp2p/blob/master/p2p/net/swarm/dial_worker.go#L88-L90) but that didn't look very clean.

**Comment by MarcoPolo** [comment]
Nice work! Let me also say that I'm sorry the dial logic is a bit messy.

While I think this PR is reasonable, I'm afraid it still misses some close cases [e.g.](https://github.com/libp2p/go-libp2p/blob/8529a340a1f1c70a0f60a0685576ca9a066c22b9/p2p/net/swarm/swarm_dial.go#L510). I think the strategy should be to make sure we make fewer calls not more, since more is an indicator that this is brittle and requires us to remember to make the right calls when things error or close. My suggestion then is to make sure we record this metric in the `.Close()` call itself. This is good for two reasons: 1. Less duplication – we can just reuse the existing Close calls to record the metric, and 2. If we notice this number being wrong we can be pretty sure that there's a connection leak issue rather than us forgetting to call this metric.

Since we're on a time crunch I'm going to push a PR with these changes. But thanks for this PR and debugging this, it helped me at least :)

**Comment by sukunrt** [comment]
> I'm afraid it still misses some close cases [e.g.](https://github.com/libp2p/go-libp2p/blob/8529a340a1f1c70a0f60a0685576ca9a066c22b9/p2p/net/swarm/swarm_dial.go#L510).

oops 

I agree. My PR has ClosedConnection calls all over the place. your change looks much cleaner. Thanks for fixing this :)

**Pull request closed without merging**
