### PR TITLE
connmgr: Use eventually equal helper in connmgr tests

### LINKED ISSUE #1687: connmgr: flaky TestTagClosure
https://github.com/libp2p/go-libp2p/actions/runs/2881461444/attempts/1

```
 === RUN   TestTagClosure
      decay_test.go:277: 
          	Error Trace:	D:\a\go-libp2p\go-libp2p\p2p\net\connmgr\decay_test.go:277
          	Error:      	Not equal: 
          	            	expected: 998
          	            	actual  : 999
          	Test:       	TestTagClosure
  --- FAIL: TestTagClosure (0.08s)

### LINKED ISSUE #1733: connmgr: flaky TestCustomFunctions
```
  === RUN   TestCustomFunctions
      decay_test.go:118: 
          	Error Trace:	D:\a\go-libp2p\go-libp2p\p2p\net\connmgr\decay_test.go:118
          	Error:      	Not equal: 
          	            	expected: 2975
          	            	actual  : 2986
          	Test:       	TestCustomFunctions
  --- FAIL: TestCustomFunctions (0.21s)

### LINKED ISSUE #1814: connmgr: flaky TestTagRemoval
https://github.com/libp2p/go-libp2p/actions/runs/3208002096/jobs/5243462395

```
  === RUN   TestTagRemoval
      decay_test.go:242: 
          	Error Trace:	/Users/runner/work/go-libp2p/go-libp2p/p2p/net/connmgr/decay_test.go:20
          	            				/Users/runner/work/go-libp2p/go-libp2p/p2p/net/connmgr/decay_test.go:242
          	Error:      	Condition never satisfied
          	Test:       	TestTagRemoval
  --- FAIL: TestTagRemoval (0.72s)

### PR DESCRIPTION
**Pull request by MarcoPolo**
These tests relied on some background goroutine doing some work. This changes the equal checks to allow the tests to pass even if the background work doesn't happen instantly.

Fixes https://github.com/libp2p/go-libp2p/issues/1324. Fixes #1687. Fixes #1733. Fixes #1814.

### CODE REVIEW

**Review by marten-seemann — APPROVED** [review]
Not a big fan of the the helper function, as it makes the assertion more difficult to read.

**Comment by MarcoPolo** [comment]
I'll add an error message

**Comment by marten-seemann** [comment]
I was suggesting to use `require.Eventually` directly.

**Comment by MarcoPolo** [comment]
How does that help? The helper function has a t.Helper call. And using eventually directly doesn't tell you the expected vs actual unless you do something similar.

**Pull request merged**
