### PR TITLE
remove unneeeded build info function in Identify

### PR DESCRIPTION
**Pull request by marten-seemann**
I'm now sure if this is actually the correct fix, but it makes our tests pass with Go 1.18.

`debug.ReadBuildInfo` didn't work in Go 1.17 (`ok` was always `false`). In Go 1.18 is now suddenly works, and is failing the TestIDService test.

### CODE REVIEW

**Review by vyzo — APPROVED** [review]
this changes the user agent, anyway around it?

**Comment by marten-seemann** [comment]
I don't think it does, as the `init` was never actually executed because `ReadBuildInfo` returned `false`. But then I'm not sure why it was introduced in the first place. @Stebalien?

**Review by Stebalien — CHANGES_REQUESTED** [review]
This is meant for setting the user agent when included in a dependency of another go module (e.g., go-ipfs). For cases like that, I believe it actually works (I thought I tested it). I believe the correct fix is to check if `bi.Main.Path` is empty.

**Comment by Stebalien** [comment]
(we should maybe document that...)

**Comment by marten-seemann** [comment]
> This is meant for setting the user agent when included in a dependency of another go module (e.g., go-ipfs). For cases like that, I believe it actually works (I thought I tested it).

That makes sense. And even better, we can now use the vcs infos that Go 1.18 makes accessible (see https://blog.carlmjohnson.net/post/2021/golang-118-minor-features/). I'll make another PR.

**Comment by marten-seemann** [comment]
There we go: https://github.com/libp2p/go-libp2p/pull/1381

**Pull request closed without merging**
