### PR TITLE
Feat/protocol prefs

### PR DESCRIPTION
**Pull request by whyrusleeping**
This adds support for remembering which of a set of protocols works for a given peer. It also uses protocols learned from the identify handshake to seed this knowledge  if available.

### CODE REVIEW

**Comment by whyrusleeping** [comment]
it appears theres actually a problem on osx here

**Comment by whyrusleeping** [comment]
alright, fixed the osx thing, apparently it was slower for OSX to close out the socket than on linux.

@Kubuxu wanna review?

**Comment by Kubuxu** [comment]
Can you add me to libp2p org so I can assign myself?

**Comment by whyrusleeping** [comment]
invite sent

**Comment by whyrusleeping** [comment]
The one thought I had here is that the preference logic should probably be moved into the peerstore.

**Comment by whyrusleeping** [comment]
@Kubuxu still review this, but i'm gonna merge it so i can move forward here.

**Comment by Kubuxu** [comment]
LGTM, it would be worth to use `protocol.ID` higher in stack instead of string but it isn't that important.

**Comment by whyrusleeping** [comment]
@Kubuxu yeah, i was thinking that too. we can do that later, it was kindof awkward to do the casting between the peerstore and multistream code

**Pull request merged**
