### PR TITLE
core/peer: remove deprecated Encode function

### PR DESCRIPTION
**Pull request by marten-seemann**

### CODE REVIEW

**Review by sukunrt — APPROVED** [review]

**Comment by marten-seemann** [comment]
Highlighting this here as well:
* Kubo: https://github.com/search?q=repo%3Aipfs%2Fkubo%20peer.Decode&type=code
* Lotus: https://github.com/search?q=repo%3Afilecoin-project%2Flotus%20peer.Decode&type=code

cc @p-shahi

**Comment by Icarus9913** [comment]
How about I commit PR for this two?
@marten-seemann

**Comment by marten-seemann** [comment]
> How about I commit PR to improve it for this two project after you release go-libp2p v0.31.z or v0.32.0? @marten-seemann

You actually don't have to wait for the release, you could do this change right now if you want to. This would make updating the new go-libp2p later easier. Please tag me in those PRs, happy to review :)

**Comment by Icarus9913** [comment]
> This would make updating the new go-libp2p later easier. Please tag me in those PRs, happy to review :)

OK, I noticed `kubo` and `lotus` still use `go-libp2p v0.30.0`, I gonna update them to `v0.31.0` and remove the deprecated method.

**Comment by marten-seemann** [comment]
> > This would make updating the new go-libp2p later easier. Please tag me in those PRs, happy to review :)
> 
> OK, I noticed `kubo` and `lotus` still use `go-libp2p v0.30.0`, I gonna update them to `v0.31.0` and remove the deprecated method.

Please don't mix those two changes. Kubo and Lotus do some network testing before updating to a new libp2p release, so that's a bigger change. Replacing the deprecated function is something that doesn't need to be tested on the live network, so it would make sense to create a PR with only that change.

**Comment by Icarus9913** [comment]
@marten-seemann 
Oh bad, I checked go-libp2p release `v0.31.0`, it looks the `peer.Encode` is still complete. And it might deprecated in the main branch. So I can't just update go-libp2p from `v0.30.0` to `v0.31.0` and remove the `peer.Encode` ?

https://github.com/libp2p/go-libp2p/blob/87a8d4e18f484d17ce8ab86a58a345d890e09609/core/peer/peer.go#L126-L146

**Pull request merged**
