### PR TITLE
retract v0.26.1, release v0.26.2

### PR DESCRIPTION
**Pull request by marten-seemann**
See https://github.com/protocol/.github/issues/481.

### CODE REVIEW

**Review by Jorropo — APPROVED** [review]
Idk how you handle your release branches but just so you know you will need to front port this onto `master` (so retract is permanent).

**Comment by Jorropo** [comment]
Also in case you missed, your examples reverted to `0.25`.

**Comment by marten-seemann** [comment]
> Also in case you missed, your examples reverted to `0.25`.

That's fine, the release branch doesn't contain https://github.com/libp2p/go-libp2p/pull/2134.

**Comment by vyzo** [comment]
what happened here, why are you retracting?

**Comment by marten-seemann** [comment]
@vyzo see https://github.com/protocol/.github/issues/481

**Comment by vyzo** [comment]
oh, ouch.

**Review by galargh — APPROVED** [review]

**Comment by p-shahi** [comment]
blocked on https://github.com/libp2p/go-libp2p/pull/2156 (for kubo 0.19)

**Comment by MarcoPolo** [comment]
Should we get https://github.com/libp2p/go-libp2p/pull/2156 in as well before this release?

**Comment by p-shahi** [comment]
@MarcoPolo @Jorropo has indicated yes. I'll made this aware to kubo maintainers here: https://github.com/ipfs/kubo/issues/9502#issuecomment-1450796071

**Comment by marten-seemann** [comment]
Rebased to include #2156.

**Review by MarcoPolo — APPROVED** [review]

**Pull request merged**
