### PR TITLE
Revert "metrics: add example for metrics and dashboard (#2232)"

### PR DESCRIPTION
**Pull request by MarcoPolo**
This reverts commit 22c45a11bb15139a0e3e18eb1e3cdb10c8cd60b9. See https://github.com/libp2p/go-libp2p/pull/2383#issuecomment-1601681566 for context

### CODE REVIEW

**Comment by sukunrt** [comment]
We should keep the example app, right? We can use the docker setup in `/dashboards`

**Comment by marten-seemann** [comment]
@MarcoPolo Can you address Sukun's comment?

**Comment by MarcoPolo** [comment]
I'll update to remove duplicates here.

**Comment by MarcoPolo** [comment]
Let's continue on #2404

**Pull request closed without merging**
