### PR TITLE
gx: update go-libp2p-peerstore

### PR DESCRIPTION
**Pull request by lgierth**
Depends on:

- https://github.com/libp2p/go-libp2p-net/pull/7
- https://github.com/libp2p/go-libp2p-metrics/pull/2
- https://github.com/libp2p/go-libp2p-host/pull/3
- https://github.com/libp2p/go-libp2p-swarm/pull/22
- https://github.com/libp2p/go-libp2p-netutil/pull/4
- https://github.com/libp2p/go-libp2p-blankhost/pull/1

### CODE REVIEW

**Comment by whyrusleeping** [comment]
@lgierth changes look good to me. Are those all pinned?

**Comment by lgierth** [comment]
All merged and pinned now :)

**Comment by lgierth** [comment]
(Note that the root package (go-libp2p) doesn't get released by gx-workspace.)

**Comment by lgierth** [comment]
Yay green now that the stuff is pinned

**Pull request merged**
