### PR TITLE
refactor: using maps.Clone

### PR DESCRIPTION
**Pull request by pengbanban**

### CODE REVIEW

**Comment by pengbanban** [comment]
> Hunting for airdrops, huh?

Of course not.  

I think this change is meaningful.

If you think this change is simple, please find a few more such cases.

**Comment by marten-seemann** [comment]
Oh look, more such “meaningful” changes…
IMG_4484

**Comment by pengbanban** [comment]
> Oh look, more such “meaningful” changes… IMG_4484

Your level is indeed high, but I don't think such optimization is meaningless, I also spent a lot of time. Please don't be sarcastic here.

**Comment by Jorropo** [comment]
image
image

the good old private repo backdating commit trick

**Comment by p-shahi** [comment]
Please refer to our open issues (especially those with help wanted labels) to find better ways to contribute https://github.com/libp2p/go-libp2p/issues

**Pull request closed without merging**
