### PR TITLE
feat: add kcp transport with listener implement 

### PR DESCRIPTION
**Pull request by derrandz**
### Description

This PR aims to introduce KCP as a supported protocol in the libp2p library

### Missing

* Metrics
* Reuseport

### CODE REVIEW

**Comment by marten-seemann** [comment]
Which issue does this resolve? I’m not convinced KCP is a good idea, but we should discuss this in an issue and not on a PR.

**Comment by marten-seemann** [comment]
There already is a 3rd party KCP transport implementation: https://github.com/paralin/go-libp2p-kcp.

**Comment by marten-seemann** [comment]
#193 was the tracking issue, and we closed it once QUIC was merged. There really shouldn’t be any reason to use KCP if you can use QUIC instead.

**Comment by derrandz** [comment]
Hi @marten-seemann thanks for the context. This was old and wanted to do a performance test against quic through libp2p to provide a rational for using kcp alongside quic or instead of quic. I would have to come with rationale and benchmark stats but closing this for now makes sense.

Cheers,

**Pull request closed without merging**
