### PR TITLE
mock: use go.uber.org/mock

### LINKED ISSUE #2528: switch away from github.com/golang/mock
It's unmaintained, and apparently Uber is maintaining a fork.

### PR DESCRIPTION
**Pull request by sukunrt**
closes #2528

### CODE REVIEW

**Review by marten-seemann — APPROVED** [review]
LGTM. Let's defer merging until we've released the HTTP fixes though, then we can cut the patch release on master and don't need to bother with backporting.

**Comment by marten-seemann** [comment]
I'm going ahead with merging. We've already merged other breaking changes.

**Comment by sukunrt** [comment]
@marten-seemann rebased my changes. Can you have a look once? I'll merge after that.

**Comment by marten-seemann** [comment]
Looks like I claimed to merge it, but I didn't actually do it. Sorry for that.

**Review by marten-seemann — APPROVED** [review]

**Pull request merged**
