### PR TITLE
Release v0.23.4

### PR DESCRIPTION
**Pull request by MarcoPolo**
- [x] todo: merge and include this: https://github.com/libp2p/go-libp2p/pull/1860

### CODE REVIEW

**Comment by p-shahi** [comment]
👍 / 👎  on including https://github.com/libp2p/go-libp2p/pull/1835

**Comment by marten-seemann** [comment]
> 👍 / 👎 on including #1835

#1835 is a new feature, so this shouldn't go into a patch release.

**Comment by marten-seemann** [comment]
image
The commit history doesn't look right. This branch should be based on top of `release-v023`, not `release-v0233` (sorry for the confusing naming!).

**Comment by MarcoPolo** [comment]
Will merge after CI passes and cut a new release

**Pull request merged**
