### PR TITLE
update deps due to license

### PR DESCRIPTION
**Pull request by ZBoIsHere**
@aarshkshah1992 Hello, we use libp2p in our open source project https://github.com/kubeedge/edgemesh, but go-libp2p-noise v0.1.1 lack of license, so I update this deps to v0.2.0

### CODE REVIEW

**Comment by Stebalien** [comment]
Fixed in https://github.com/libp2p/go-libp2p/pull/1141.

**Comment by Stebalien** [comment]
Ah, wait, you were using a forked branch? That just needs to be rebased.

**Comment by Stebalien** [comment]
But you also _really_ shouldn't be using that in a deployed project. That branch will disappear.

**Comment by Stebalien** [comment]
Well, no reason _not_ to merge this. It could cause some conflicts, but not likely.

**Comment by ZBoIsHere** [comment]
I found that other package like github.com/libp2p/go-yamux v0.5.1 exist the same problem

**Comment by ZBoIsHere** [comment]
thanks, @Stebalien  I plan to  edit the go.mod file in my forked branch, and import the edited branch in our project. when the feature branch about hole punch merged into master, I will re-import the master branch

**Pull request merged**
